### ISSUE TITLE
preview.adonisjs.com navigation bug.

### ISSUE THREAD

**Issue by zarkones** [adonisjs/legacy.adonisjs.com#101]
It happens sometimes that routing doesn't work.
While the page is loading, try to spam the buttons, this seems to reproduce the bug. (It happens also without spamming sometimes)
Application gets stuck at the current page, unable to redirect. 

And when navigation link is clicked console prompts us with `TypeError: t.$context.doc.meta is null`  pointing at `https://preview.adonisjs.com/assets/js/page--src--templates--blog-vue.07a3fa08.js:1`

Yet, I was able to reproduce the issue once without triggering any errors in the console. Which was strange.

And I want to mention that I've experienced this behavior under the page 'Guides' while selecting sections.
For example clicking on a different section will change the website's path, but not the actual view.

Thank you for reading.

**Comment by McSneaky** [comment]
Had the same issue today, it seems to be coming from ServiceWorker somehow on Chromium browser

```
service-worker.js:1 Uncaught ReferenceError: cacheOnly is not defined
    at service-worker.js:1
    at service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
```

After deleting service worker and refreshing page I get two errors

```
Uncaught ReferenceError: cacheOnly is not defined
    at service-worker.js:1
    at service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1


service-worker.js:1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('https://preview.adonisjs.com/') with script ('https://preview.adonisjs.com/service-worker.js'): ServiceWorker script evaluation failed
Promise.then (async)
n @ service-worker.js:1
c @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
(anonymous) @ service-worker.js:1
```

It's quite easy to reproduce. Just go to https://preview.adonisjs.com/ and click on any of the header link. `Guides` for an example. To actually get to Guides have to click on Guides and then refresh the page

**Comment by RomainLanz** [comment]
Hey there! 👋 

It's not an issue with the service worker.
We had an issue with our hosting provider and needed to switch. We don't know why but this navigation issue appears with Netlify.

It seems to be an issue with Gridsome directly and the generated HTML.
Nevertheless, we are preparing a brand new website that will fix all of this.

Sorry for the inconvenience.

**Comment by thetutlage** [comment]
Yeah, its sad that all of this is broken for now. Planning to push the fix over the weekend. Kudos to @RomainLanz for putting in all the time :)

**Comment by skrenek** [comment]
If this is talking about the nav links not working when you click them (Guides, for example, the browser url updates, but no nav happens), then my workaround is to focus the browser nav bar and then hit enter.  It seems the new server wants a trailing slash.  Hopefully this helps someone until fixed / replaced.

**Comment by zarkones** [comment]
@skrenek 

You're correct, adding a trailing slash fixes all the issues together.
Maybe the app can be configured to add trailing slash against a url, if not present at the end of the path? @thetutlage
