### ISSUE TITLE
Mistake in docs HasManyThrough

### ISSUE THREAD

**Issue by yariksav** [adonisjs/legacy.adonisjs.com#108]
Hello!
THank you for awesome Lucid new version! It's great!

Seems to be mistake in has many through documentation

https://github.com/adonisjs/adonisjs.com/blob/develop/docs/docs/guides/database/04-relationships/06-has-many-through-relationship.md
```
export default class Country extends BaseModel {
  @hasManyThrough(() => Post, () => User)
  public posts: HasManyThrough<typeof Post>
}
```
instead
```
export default class Country extends BaseModel {
  @hasManyThrough([() => Post, () => User])
  public posts: HasManyThrough<typeof Post>
}
```
First parameter is array of two elements
```
export const hasManyThrough: HasManyThroughDecorator = ([relatedModel, throughModel], relation) 
```
https://github.com/adonisjs/lucid/blob/dc620118690962e9c5cac6c5be0d830f0191027d/src/Orm/Decorators/index.ts#L121

Thank you!

**Comment by thetutlage** [comment]
Yup. Mind opening a PR for the fix?

**Comment by yariksav** [comment]
Hi, @thetutlage!
Ok, almost done, but I have to clarify descriptions of options fields
As I wrote

## Relationship keys
A many to many through relation relies on many different keys to properly setup the relationship. All of these are keys are computed using standard conventions. However, you are free to override them.

### `localKey`
The local key is mostly the primary key of the **first model**. In our example: Country is the first model and `localKey` will be the `id`.

### `foreignKey`
The foreign key is in the pivot table to create the relationship with the **first model**. Conventionally, it is **snake_case** representation of the model name and its primary key. In our example: The `foreignKey` will be `country_id`.

### `throughLocalKey`
The related foreign key is in the pivot table to create the relationship with the **related model**. Conventionally, it is **snake_case** representation of the model name and its primary key. In our example: The `throughLocalKey` will be `id`.

### `throughForeignKey`
The through foreign key is mostly the foreign key of the **related model**. In our example: Skill is the related model and `throughForeignKey` will also be the `user_id`.

```ts
@manyToMany([() => Post, () => User], {
  localKey: 'id',
  foreignKey: 'country_id',
  throughLocalKey: 'id',
  throughForeignKey: 'user_id'
})
public posts: HasManyThrough<typeof Post>
```

Please correct if there something wrong

**Comment by thetutlage** [comment]
Looks perfect to me

**Comment by yariksav** [comment]
closed by https://github.com/adonisjs/adonisjs.com/pull/109
