### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by nioperas06** [adonisjs/legacy.adonisjs.com#16]
https://github.com/adonisjs/adonisjs.com/blob/8b1fae27f2d3408bd7bbf6aa33c8292c80fc2d97/resources/views/partials/apps.edge#L21

**Comment by jakesylvestre** [comment]
Maybe we could replace this with something from [here](https://github.com/zgabievi/awesome-adonisjs#articles-tutorials-blogs-etc)

**Comment by RomainLanz** [comment]
Fixed!
