### ISSUE TITLE
Minor spelling errors and fix ease-of-reading

### ISSUE THREAD

**Issue by parker-codes** [adonisjs/legacy.adonisjs.com#18]
I'm submitting a PR for these items, but I wanted to document it via this issue. Love the framework by the way, and I hope to become a long-time contributor!

## Site

![adonisjs_official_packages](https://user-images.githubusercontent.com/17652149/46817263-a7615480-cd33-11e8-93fd-2af60cafcc2a.png)
![adonisjs_official_packages 2](https://user-images.githubusercontent.com/17652149/46817276-ad573580-cd33-11e8-9302-2dc89c41a59d.png)
![adonisjs_official_packages 3](https://user-images.githubusercontent.com/17652149/46817289-b0eabc80-cd33-11e8-8081-4e5fb473b608.png)

## README

![adonisjs_adonisjs_com__the_website_for_adonisjs_com 2](https://user-images.githubusercontent.com/17652149/46817294-b516da00-cd33-11e8-9367-fa5a054adf4c.png)
![adonisjs_adonisjs_com__the_website_for_adonisjs_com 2](https://user-images.githubusercontent.com/17652149/46817342-c7911380-cd33-11e8-80a1-b6452551f13b.png)
![adonisjs_adonisjs_com__the_website_for_adonisjs_com 3](https://user-images.githubusercontent.com/17652149/46817374-d7a8f300-cd33-11e8-92bf-9ded9b0b9778.png)

**Comment by thetutlage** [comment]
Impressed 😄
