### ISSUE TITLE
Add a Direct link to Github repo from Adonisjs.com Homepage

### ISSUE THREAD

**Issue by SNaushadS** [adonisjs/legacy.adonisjs.com#24]
Not a bug neither a Feature. This is just a feedback about adonis homepage.

I saw the design request on opensourcedesign jobs > checked adonis site > found that the Github repo link is hidden 3 layers.

I understand developers would benefit if the github link is available quicker. User has to click on Get Started and at the lower end section there is a small text link.

As compared to other framework sites, where github star button and repo link are readily available without any interaction.

Example : React Js
Look at the explicit Github Link in top right.

![image](https://user-images.githubusercontent.com/1532907/47950690-baa2c100-df7b-11e8-81e5-b1285b3a9de6.png)

I had initially created this issue in AdonisJS Framework repo [Adonis Framework : Issue 995](https://github.com/adonisjs/adonis-framework/issues/995)

**Comment by thetutlage** [comment]
Yes, surely!

The Github link should be visible as top level navigation. Feel free to share a PR for same, if you have time 😄

**Comment by RomainLanz** [comment]
There's already a PR for that, https://github.com/adonisjs/adonisjs.com/pull/23.

Closing in favour of the PR.
