### ISSUE TITLE
Site won't run locally

### ISSUE THREAD

**Issue by octoxan** [adonisjs/legacy.adonisjs.com#25]
`adonis serve --dev` has no output. Can't access at localhost:3000 or anything. Following exact commands from the readme, on Ubuntu.

**Comment by RomainLanz** [comment]
Hey @octoxan! 👋 

Do you still have the issue?
I don't have any problem on my side to run this repository locally.

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
