### ISSUE TITLE
Module 4.0 not cloned

### ISSUE THREAD

**Issue by woodgates** [adonisjs/legacy.adonisjs.com#27]
After running git submodule update all the modules up to version 3 are cloned.

The this error message appears:

> Cloning into '/home/jorge/Dropbox/www/adonisjs.com/content/4.1'...
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

**Comment by RomainLanz** [comment]
Hey @woodgates! 👋 

Is this still an issue?

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
