### ISSUE TITLE
Double curly brackets

### ISSUE THREAD

**Issue by anonimusprogramus** [adonisjs/legacy.adonisjs.com#34]
One of the example causing error due to (maybe) Edge's regex that it assumes Double curly brackets as Mustache braces.

I just opened issue on [Edge's repo](https://github.com/edge-js/edge/issues/67) too.

**Recreating steps:**

1. Open [Named Route Docs](https://adonisjs.com/docs/4.1/routing#_named_route)

2. There is this example:

> The same rules apply for the view.
>
> `<a href="{{ route('posts.show', { id: 1 }, {query: { foo: 'bar' }}) }}">Show post</a>`
> 
> `// href="/post/1?foo=bar"`

3. Try running it, you'd get error:

`InvalidExpressionException
E_INVALID_EXPRESSION: Invalid expression < route('posts.show', { id: 1 }, {query: { foo: 'bar' >`

4. Now separate those double curly brackets with **one space char**:

`{query: { foo: 'bar' }}` become `{query: { foo: 'bar' } }`

5. Re-run, now it works.

**Comment by LeNiglo** [comment]
Agreed.
This is weird and not intuitive at all.

Furthermore, the querystring isn't set accordingly using this exemple ...

**Comment by RomainLanz** [comment]
Fixed in v5.
