### ISSUE TITLE
Website inaccessible from networks of AS9198 (Kazakhtelecom)

### ISSUE THREAD

**Issue by baybal** [adonisjs/legacy.adonisjs.com#41]
Hello,

It seems that your ISP is null routing requests from networks of AS9198 (Kazakhtelecom).

Would it be possible for you to check on that with your hosting provider/ISP?

**Comment by RomainLanz** [comment]
Hey @baybal! 👋 

I believe the website run over Cloudflare Network, do you know any issue with Cloudflare and your network?

**Comment by baybal** [comment]
No, none. I have no problem connecting to other websites going through cloudflare

**Comment by baybal** [comment]
Can you add an AS to a whitelist in the settings?

**Comment by RomainLanz** [comment]
Hey!

How it's doing now with the new website?
You can also try using the `Now` url: https://adonisjs-com.now.sh/

**Comment by baybal** [comment]
Works now

**Comment by RomainLanz** [comment]
Nice to hear!
