### ISSUE TITLE
Search in preview website not working properly 

### ISSUE THREAD

**Issue by pikitgb** [adonisjs/legacy.adonisjs.com#59]
Hi Guys!, loving this new documentation thanks a lot. 
When trying to search in new Website, i'm seeing this error in the console.

![image](https://user-images.githubusercontent.com/2738018/80914737-8ac4ad00-8d1b-11ea-9488-67e5cbf9ae41.png)

**Comment by RomainLanz** [comment]
Hey @pikitgb! 👋 

The search hasn't been implemented yet.
@thetutlage, should we remove it from the UI in the meanwhile?

**Comment by RomainLanz** [comment]
Search is now working!
