### ISSUE TITLE
Add sections for deployment

### ISSUE THREAD

**Issue by guledali** [adonisjs/legacy.adonisjs.com#61]
Have simple guide on how to deploy an `adonisjs` application with db to [Heroku](https://www.heroku.com/) or [DigitalOcean](https://www.digitalocean.com/)

Or maybe having a cookbook section with recipes that shows examples on how to integrate with 3-party services and more.

**Comment by RomainLanz** [comment]
Hey @guledali! 👋 

Thanks for your suggestion.
I have created [a Trello card](https://trello.com/c/AN0vIfbU/32-completing-deployment-documentation) to keep track of this.
