### ISSUE TITLE
Insecure link (http link) to image

### ISSUE THREAD

**Issue by hholst80** [adonisjs/legacy.adonisjs.com#70]
Wrong link in https://adonisjs.com/screencasts

`http://res.cloudinary.com/adonisjs/image/upload/q_100/v1521629831/codecourse-adonis_nylt0m.jpg`

should be 

`//res.cloudinary.com/adonisjs/image/upload/q_100/v1521629831/codecourse-adonis_nylt0m.jpg`

**Comment by prondubuisi** [comment]
Hello @RomainLanz , where is the screencasts page located? I looked through this folder but I can't find it

**Comment by RomainLanz** [comment]
Hey there! 👋 

All of this is in the old website.
We do not plan to update it for the moment since it's going to be replaced.

**Comment by prondubuisi** [comment]
Great!
