### ISSUE TITLE
Create task for writing Provider guide?

### ISSUE THREAD

**Issue by jacobq** [adonisjs/legacy.adonisjs.com#74]
I am new to Adonis and am jumping right into the 5.0 preview. Is there (going to be) a guide related to Providers? i.e. something like https://adonisjs.com/docs/4.1/service-providers
I don't see it on the Trello list or the [new guides](https://preview.adonisjs.com/guides/).

**Comment by RomainLanz** [comment]
Hey @jacobq! 👋 

The card on Trello is here: https://trello.com/c/x8SCwZR9
In the meanwhile, you can join our [Discord Server](https://discord.gg/vDcEjq6) and get help if you have any questions on how to create a provider!
